version: "3.9"
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - "TZ=Europe/Amsterdam"
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=admin"
    ports:
      - "5432:5432"
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
